services:
  - type: web
    name: smartshroom
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn final_smartshroom.wsgi:application --bind 0.0.0.0:$PORT --timeout 120"
    envVars:
      - key: DEBUG
        value: "False"
      - key: DJANGO_SETTINGS_MODULE
        value: final_smartshroom.settings