services:
  - type: web
    name: smartshroom
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn smartshroom.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: smartshroom.settings
      - key: PYTHON_VERSION
        value: 3.10.12
